version: '3.8'

services:
  express-app:
    container_name: tokotitoh-api
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
networks:
  web:
    external: true